include $(SRC_RT)/myOS/kernel/task/scheduler/Makefile

TASK_OBJS =	output/myOS/kernel/task/idleTsk.o \
		output/myOS/kernel/task/initTsk.o \
		output/myOS/kernel/task/state.o \
		output/myOS/kernel/task/task.o \
		output/myOS/kernel/task/taskQueue.o \
		output/myOS/kernel/task/tskManagerInit.o \
		$(SCHEDULE_OBJS)